baseURL = "https://ismailcanoguz.fr/"
canonifyURLs = true
title = "Ismail Can Oguz"
languageCode = "en"
defaultContentLanguage = "en"
theme = "blowfish"
enableRobotsTXT = true

[params]
description = "ML for Materials (DFT + GNNs) · Research Engineer / Data Scientist · Postdoc @ DIFFER"
images = ["og/cover.png"]

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]
