[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Research"
  pageRef = "research"
  weight = 20

[[main]]
  name = "Publications"
  pageRef = "publications"
  weight = 30

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 40

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 50

[[main]]
  name = "Hobbies"
  pageRef = "hobbies"
  weight = 60

[[main]]
  name = "CV (PDF)"
  url = "/files/CV_Oguz.pdf"
  weight = 70


